# Generated by Django 2.2.4 on 2019-08-19 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime'),
        ),
        migrations.AddField(
            model_name='cat',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='sex',
            field=models.CharField(default=None, max_length=1, verbose_name='Sex'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cat',
            name='birthday',
            field=models.DateField(verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.CharField(max_length=30, verbose_name='breed'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.TextField(verbose_name='Name'),
        ),
    ]
