# Generated by Django 2.2.4 on 2019-08-19 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cat_app', '0002_auto_20190819_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='birthday',
            field=models.DateField(verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.CharField(max_length=30, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.TextField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='sex',
            field=models.CharField(choices=[('m', 'мужской'), ('w', 'женский')], max_length=1, verbose_name='Пол'),
        ),
    ]
