# Generated by Django 2.2.4 on 2019-08-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_app', '0003_auto_20190819_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлен'),
        ),
    ]
